seed: 42
gpu: all
data:
  dataset: S1_2_CR_Data
  root_imgs: /data/docker/volumes/laclasse/SEN12MS-CR/
  input: /augmented
  batch_size: 512
  num_workers: 32
train:
  model:
    name: DSen2-CR
    kwargs:
      input_channels: 15
      output_channels: 13
  start_epoch: 1
  epochs: 2000
  checkpoint:
    path:
    model:
  criterion: MSELoss
  optimizer:
    name: Adam
    kwargs:
      lr: 0.00001
      weight_decay: 0.00005
      betas: [0.9, 0.999]