seed: 42
gpu: 1
data:
  dataset: S1_2_CR_Data
  root_imgs: /data/
  input: /inputs/single/
  batch_size: 8
  num_workers: 20
train:
  start_epoch: 1
  epochs: 2000
  checkpoint:
    path: models/
    model: Difuser
  criterion: MSELoss
  optimizer:
    name: Adam
    kwargs:
      lr: 0.00001
      weight_decay: 0.00005
      betas: [0.9, 0.999]